// packages/vue/src/EmbedSkeleton.vue
<script setup lang="ts">
import type { EmbedSkeletonProps } from './types';

/**
 * Loading skeleton component for Flat Embed
 *
 * @example
 * ```vue
 * <FlatEmbed score="..." app-id="...">
 *   <template #loading>
 *     <EmbedSkeleton animated />
 *   </template>
 * </FlatEmbed>
 * ```
 *
 * @example Standalone usage
 * ```vue
 * <EmbedSkeleton v-if="!isReady" height="600px" pulse />
 * ```
 */

const props = withDefaults(defineProps<EmbedSkeletonProps>(), {
  width: '100%',
  height: '600px',
  animated: true,
  pulse: false,
});
</script>

<template>
  <div
    class="embed-skeleton"
    :class="{
      'embed-skeleton--animated': props.animated && !props.pulse,
      'embed-skeleton--pulse': props.animated && props.pulse,
    }"
    :style="{
      width: props.width,
      height: props.height,
    }"
    aria-label="Loading sheet music embed"
  >
    <!-- Header skeleton -->
    <div class="embed-skeleton__header">
      <div class="embed-skeleton__bar" style="width: 40%; height: 20px" />
      <div class="embed-skeleton__bar" style="width: 30%; height: 16px; margin-top: 8px" />
    </div>

    <!-- Staff lines skeleton -->
    <div class="embed-skeleton__staff">
      <div v-for="i in 5" :key="i" class="embed-skeleton__staff-line" />
    </div>

    <!-- Controls skeleton -->
    <div class="embed-skeleton__controls">
      <div class="embed-skeleton__button" style="width: 40px; height: 40px; border-radius: 50%" />
      <div class="embed-skeleton__bar" style="flex: 1; height: 4px; margin: 0 16px" />
      <div class="embed-skeleton__button" style="width: 32px; height: 32px" />
      <div class="embed-skeleton__button" style="width: 32px; height: 32px" />
    </div>

    <!-- Shimmer effect -->
    <div v-if="props.animated && !props.pulse" class="embed-skeleton__shimmer">
      <div class="embed-skeleton__shimmer-gradient" />
    </div>
  </div>
</template>

<style scoped>
.embed-skeleton {
  background-color: #f0f0f0;
  border-radius: 4px;
  overflow: hidden;
  position: relative;
}

.embed-skeleton__header {
  padding: 24px;
}

.embed-skeleton__bar {
  background-color: #e0e0e0;
  border-radius: 4px;
}

.embed-skeleton__staff {
  padding: 40px 24px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.embed-skeleton__staff-line {
  height: 1px;
  background-color: #d0d0d0;
}

.embed-skeleton__controls {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 60px;
  background-color: #fafafa;
  border-top: 1px solid #e0e0e0;
  display: flex;
  align-items: center;
  padding: 0 16px;
  gap: 8px;
}

.embed-skeleton__button {
  background-color: #e0e0e0;
  border-radius: 4px;
}

.embed-skeleton--pulse {
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

.embed-skeleton__shimmer {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
}

.embed-skeleton__shimmer-gradient {
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, rgba(255,255,255,0.5), transparent);
  animation: shimmer 2s infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

@keyframes shimmer {
  0% { transform: translateX(0); }
  100% { transform: translateX(200%); }
}
</style>

// packages/react/src/EmbedSkeleton.tsx
import React from 'react';
import type { EmbedSkeletonProps } from './types';

/**
 * Loading skeleton component for Flat Embed
 *
 * @example
 * ```tsx
 * <FlatEmbed
 *   score="..."
 *   appId="..."
 *   loading={<EmbedSkeleton animated />}
 * />
 * ```
 *
 * @example Standalone usage
 * ```tsx
 * {!isReady && <EmbedSkeleton height="600px" pulse />}
 * ```
 */
export function EmbedSkeleton({
  width = '100%',
  height = '600px',
  animated = true,
  pulse = false,
  className,
  style,
}: EmbedSkeletonProps) {
  const animationStyle = animated
    ? pulse
      ? pulseAnimation
      : shimmerAnimation
    : {};

  const containerStyle: React.CSSProperties = {
    width,
    height,
    backgroundColor: '#f0f0f0',
    borderRadius: '4px',
    overflow: 'hidden',
    position: 'relative',
    ...animationStyle,
    ...style,
  };

  return (
    <div className={className} style={containerStyle} aria-label="Loading sheet music embed">
      {/* Header skeleton */}
      <div style={headerStyle}>
        <div style={{ ...barStyle, width: '40%', height: '20px' }} />
        <div style={{ ...barStyle, width: '30%', height: '16px', marginTop: '8px' }} />
      </div>

      {/* Staff lines skeleton */}
      <div style={staffContainerStyle}>
        {[0, 1, 2, 3, 4].map((i) => (
          <div key={i} style={staffLineStyle} />
        ))}
      </div>

      {/* Controls skeleton */}
      <div style={controlsStyle}>
        <div style={{ ...buttonSkeletonStyle, width: '40px', height: '40px', borderRadius: '50%' }} />
        <div style={{ ...barStyle, flex: 1, height: '4px', margin: '0 16px' }} />
        <div style={{ ...buttonSkeletonStyle, width: '32px', height: '32px' }} />
        <div style={{ ...buttonSkeletonStyle, width: '32px', height: '32px' }} />
      </div>

      {/* Shimmer effect */}
      {animated && !pulse && (
        <div style={shimmerOverlayStyle}>
          <div style={shimmerGradientStyle} />
        </div>
      )}
    </div>
  );
}

// Styles
const headerStyle: React.CSSProperties = {
  padding: '24px',
};

const barStyle: React.CSSProperties = {
  backgroundColor: '#e0e0e0',
  borderRadius: '4px',
};

const staffContainerStyle: React.CSSProperties = {
  padding: '40px 24px',
  display: 'flex',
  flexDirection: 'column',
  gap: '16px',
};

const staffLineStyle: React.CSSProperties = {
  height: '1px',
  backgroundColor: '#d0d0d0',
};

const controlsStyle: React.CSSProperties = {
  position: 'absolute',
  bottom: '0',
  left: '0',
  right: '0',
  height: '60px',
  backgroundColor: '#fafafa',
  borderTop: '1px solid #e0e0e0',
  display: 'flex',
  alignItems: 'center',
  padding: '0 16px',
  gap: '8px',
};

const buttonSkeletonStyle: React.CSSProperties = {
  backgroundColor: '#e0e0e0',
  borderRadius: '4px',
};

const shimmerAnimation: React.CSSProperties = {
  animation: 'none', // Handled by overlay
};

const pulseAnimation: React.CSSProperties = {
  animation: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
};

const shimmerOverlayStyle: React.CSSProperties = {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  overflow: 'hidden',
};

const shimmerGradientStyle: React.CSSProperties = {
  position: 'absolute',
  top: 0,
  left: '-100%',
  width: '100%',
  height: '100%',
  background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.5), transparent)',
  animation: 'shimmer 2s infinite',
};

// Add keyframes via style tag
if (typeof document !== 'undefined') {
  const styleTag = document.createElement('style');
  styleTag.textContent = `
    @keyframes pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.5; }
    }

    @keyframes shimmer {
      0% { transform: translateX(0); }
      100% { transform: translateX(200%); }
    }
  `;
  // Only add if not already present
  if (!document.querySelector('[data-flat-embed-skeleton-styles]')) {
    styleTag.setAttribute('data-flat-embed-skeleton-styles', 'true');
    document.head.appendChild(styleTag);
  }
}
