// packages/vue/src/FlatEmbedProvider.vue
<script setup lang="ts">
import type Embed from "flat-embed";
import { provide, ref } from "vue";
import { FlatEmbedContextKey } from "./composables/useFlatEmbedContext";
import type { FlatEmbedContextValue, FlatEmbedProviderProps } from "./types";

/**
 * Provider for managing multiple FlatEmbed instances
 *
 * @example
 * ```vue
 * <FlatEmbedProvider app-id="your-app-id">
 *   <FlatEmbed id="main" score="score-1" />
 *   <FlatEmbed id="reference" score="score-2" />
 *   <GlobalControls />
 * </FlatEmbedProvider>
 *
 * <script setup>
 * import { useFlatEmbedContext } from '@flat/embed-vue';
 *
 * const { embeds } = useFlatEmbedContext();
 *
 * const playAll = async () => {
 *   await Promise.all(
 *     Object.values(embeds.value).map(e => e?.play())
 *   );
 * };
 * ```
 */

const props = defineProps<FlatEmbedProviderProps>();

const embeds = ref<Record<string, Embed | null>>({});

const registerEmbed = (id: string, embed: Embed) => {
	embeds.value = { ...embeds.value, [id]: embed };
};

const unregisterEmbed = (id: string) => {
	const { [id]: _, ...rest } = embeds.value;
	embeds.value = rest;
};

const getEmbed = (id: string) => {
	return embeds.value[id] ?? null;
};

const contextValue: FlatEmbedContextValue = {
	embeds,
	getEmbed,
	registerEmbed,
	unregisterEmbed,
	appId: props.appId,
};

// Provide context
provide(FlatEmbedContextKey, contextValue);
</script>

<template>
  <slot />
</template>

// packages/react/src/FlatEmbedProvider.tsx
import React, { createContext, useContext, useState, useCallback, useMemo } from 'react';
import type Embed from 'flat-embed';
import type { FlatEmbedContextValue, FlatEmbedProviderProps } from './types';

const FlatEmbedContext = createContext<FlatEmbedContextValue | null>(null);

/**
 * Provider for managing multiple FlatEmbed instances
 *
 * @example
 * ```tsx
 * <FlatEmbedProvider appId="your-app-id">
 *   <FlatEmbed id="main" score="score-1" />
 *   <FlatEmbed id="reference" score="score-2" />
 *   <GlobalControls />
 * </FlatEmbedProvider>
 *
 * function GlobalControls() {
 *   const { embeds } = useFlatEmbedContext();
 *
 *   const playAll = async () => {
 *     await Promise.all(
 *       Object.values(embeds).map(e => e?.play())
 *     );
 *   };
 *
 *   return <button onClick={playAll}>Play All</button>;
 * }
 * ```
 */
export function FlatEmbedProvider({ children, appId, locale }: FlatEmbedProviderProps) {
  const [embeds, setEmbeds] = useState<Record<string, Embed | null>>({});

  const registerEmbed = useCallback((id: string, embed: Embed) => {
    setEmbeds((prev) => ({ ...prev, [id]: embed }));
  }, []);

  const unregisterEmbed = useCallback((id: string) => {
    setEmbeds((prev) => {
      const { [id]: _, ...rest } = prev;
      return rest;
    });
  }, []);

  const getEmbed = useCallback((id: string) => {
    return embeds[id] ?? null;
  }, [embeds]);

  const value = useMemo<FlatEmbedContextValue>(
    () => ({
      embeds,
      getEmbed,
      registerEmbed,
      unregisterEmbed,
      appId,
    }),
    [embeds, getEmbed, registerEmbed, unregisterEmbed, appId]
  );

  return <FlatEmbedContext.Provider value={value}>{children}</FlatEmbedContext.Provider>;
}

/**
 * Hook to access the FlatEmbedContext
 *
 * @example
 * ```tsx
 * function MyComponent() {
 *   const { embeds, getEmbed } = useFlatEmbedContext();
 *
 *   const mainEmbed = getEmbed('main');
 *   const handlePlay = () => mainEmbed?.play();
 *
 *   return <button onClick={handlePlay}>Play</button>;
 * }
 * ```
 */
export function useFlatEmbedContext(): FlatEmbedContextValue | null {
  return useContext(FlatEmbedContext);
}
